//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirusAquarium.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BehaviorBundle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BehaviorBundle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirusAquarium.Resources.BehaviorBundle", typeof(BehaviorBundle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twiddling thumbs.
        /// </summary>
        internal static string AI_Status_Idle1 {
            get {
                return ResourceManager.GetString("AI_Status_Idle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipping coffee.
        /// </summary>
        internal static string AI_Status_Idle2 {
            get {
                return ResourceManager.GetString("AI_Status_Idle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staring longingly at screen.
        /// </summary>
        internal static string AI_Status_Idle3 {
            get {
                return ResourceManager.GetString("AI_Status_Idle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading War and Peace.
        /// </summary>
        internal static string AI_Status_Idle4 {
            get {
                return ResourceManager.GetString("AI_Status_Idle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Home.
        /// </summary>
        internal static string Virus_Status_CallingHome {
            get {
                return ResourceManager.GetString("Virus_Status_CallingHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Virus_Status_Default {
            get {
                return ResourceManager.GetString("Virus_Status_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivering Payload.
        /// </summary>
        internal static string Virus_Status_DeliveringPayload {
            get {
                return ResourceManager.GetString("Virus_Status_DeliveringPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frozen.
        /// </summary>
        internal static string Virus_Status_Frozen {
            get {
                return ResourceManager.GetString("Virus_Status_Frozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passive.
        /// </summary>
        internal static string Virus_Status_Passive {
            get {
                return ResourceManager.GetString("Virus_Status_Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Botnet.
        /// </summary>
        internal static string Virus_Status_RunningBotnet {
            get {
                return ResourceManager.GetString("Virus_Status_RunningBotnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreading.
        /// </summary>
        internal static string Virus_Status_Spreading {
            get {
                return ResourceManager.GetString("Virus_Status_Spreading", resourceCulture);
            }
        }
    }
}
